setwd("~/EEB_2016-2018/NJ_tree")

```{r}
if (!require("ape")) install.packages("ape")
library(ape)

if (!require("ggpubr")) install.packages("ggpubr")
library(ggpubr)

```


```{r}
# Used genetic distances by individual generated in GenALex to show tree
m <- read.table("GD_indiv.csv", sep = ",", header = T, row.names=165)
m <- as.matrix(m)
sheepnose <- nj(as.dist(m))
plot(sheepnose, type="phylogram")

# Used genetic distances by site generated in GenALex to show tree
n <- read.table("GD_pop.csv", sep = ",", header = T, row.names=8)
n <- as.matrix(n)
sheepnose2 <- nj(as.dist(n))
plot(sheepnose2, type="unrooted")

# Using Nei Genetic Distance
nei <- (read.table("GD_pop_Nei.csv", sep = ",", header = T, row.names=8))
nei <- as.matrix(nei)
sheepnose3 <- nj(as.dist(nei))
attach(sheepnose3)
par(mfrow=c(1,3)) 
plot(sheepnose3, type="unrooted")
plot(sheepnose3, type="cladogram")
plot(sheepnose3, type="phylogram")
```


# Pop Gen in R tutorial
```{r}
install.packages(c("poppr", "mmod", "magrittr", "treemap"), repos = "http://cran.rstudio.com", dependencies = TRUE)
library("poppr")
library("pegas")
library("lattice")
library("magrittr")
library("hierfstat")
library("mmod")

genalex <- read.genalex("GenAlex_genos.csv")
genalex

# Genotype curve
gac <- genotype_curve(genalex, sample = 1000, quiet = TRUE)

# Allele frequencies
genlt <- locus_table(genalex)
genlt
write.table(genlt, file = "allele_freqs.csv", sep = ",", quote = FALSE, row.names = T)

# Percent missing data per locus
info_table(genalex, type = "missing", plot = TRUE)

# Test for HWE
nanhwe.pop <- seppop(genalex) %>% lapply(hw.test, B = 0)
nanhwe.mat <- sapply(nanhwe.pop, "[", i = TRUE, j = 3)
alpha  <- 0.05
newmat <- nanhwe.mat
newmat[newmat > alpha] <- 1
## Heat map of loci that are out of HWE
levelplot(t(newmat))

# Test for linkage disequilibrium
ALL <- popsub(genalex, "ALL")
ia(ALL, sample = 999)
## 
CHIP <- popsub(genalex, "CHIP")
ia(CHIP, sample = 999)
## 
MER <- popsub(genalex, "MER")
ia(MER, sample = 999)
## 
MISS <- popsub(genalex, "MISS")
ia(MISS, sample = 999)
## 
TIPP <- popsub(genalex, "TIPP")
ia(TIPP, sample = 999)
## Potential for LD?
TN <- popsub(genalex, "TN")
ia(TN, sample = 999)
##
WIS <- popsub(genalex, "WIS")
ia(WIS, sample = 999)
##

# AMOVA by site
genAM <- as.genclone(genalex)
table(strata(genAM, ~Pop))
genAM <- poppr.amova(genAM, ~Pop)
set.seed(1999)
genAMsignif   <- randtest(genAM, nrepet = 999)
plot(genAMsignif)

# Private alleles
private_alleles(genalex, locus ~ Pop, count.alleles = TRUE)
pal <- private_alleles(genalex, locus ~ Pop, count.alleles = FALSE)
sweep(pal, 2, nAll(genalex)[colnames(pal)], FUN = "/")
library("ggplot2")
priv <- private_alleles(genalex, report = "data.frame")
ggplot(priv) + geom_tile(aes(x = population, y = allele, fill = count))

# Observed and expected Het
div <- summary(genalex)
div

# Plot Obs and loci number
plot(div$Hobs, xlab="Loci number", ylab="Observed Heterozygosity", 
     main="Observed heterozygosity per locus")

# Plot OBs and Expected
plot(div$Hobs, div$Hexp, xlab="Observed Heterozygosity", ylab="Expected Heterozygosity", 
     main="Expected heterozygosity as a function of observed heterozygosity per locus")

# Plot bartlett test of homogeneity between loci
bartlett.test(list(div$Hexp, div$Hobs))

#
genalex.hfstat <- genind2hierfstat(genalex)
basicstat <- basic.stats(genalex, diploid = TRUE, digits = 2)
basicstat
names(basicstat)
boot.ppfis(genalex.hfstat) 

#
x <- indpca(genalex.hfstat) 
plot(x, cex = 0.7)

# HWE
hw.test(genalex, B = 1000)

# Pairwise Jost D
install.packages("FinePop")
library(FinePop)

popdata <- read.genepop(genepop="Genepop_woPigtoe.txt")
result.DJ <- DJ(popdata)
write.csv(result.DJ, "result_DJ.csv", na="")
print(as.dist(result.DJ))
```

