# This code was used manipulate data the older mtDNA dataset.

## Set working directory
```{r}
setwd("~/EEB_2016-2018/mtDNA")
```

## Load libraries
```{r}
library(readr)
install.packages("seqinr")
library(seqinr)
install.packages("haplotypes")
library(haplotypes)
install.packages("seqRFLP")
library("seqRFLP")
```


## Reading fasta file
```{r}
seqs <- read.fasta("mtDNAsheepnose_edited.fasta", as.string = T, forceDNAtolower = FALSE)

seqdf <- as.data.frame(matrix(ncol = 2))
i=1
seqdf[i,1] <- getName(seqs[i])
seqdf[i,2] <- getSequence(seqs[i], as.string = T)
for (i in 1:length(seqs)){
  seqdf[i,1] <- getName(seqs[i])
seqdf[i,2] <- getSequence(seqs[i], as.string = T)
}

#sample_id<-data.frame(getName(seqs))
#extracted_seqs <- getSequence(seqs, as.string = T)
#seqdf <- cbind(sample_id, extracted_seqs)
colnames(seqdf)<-c("Sample_ID","Sequences")
#seqdf <- seqdf[,-c(3:160)]
#seqdftemp <- as.data.frame(t(seqdf[1,]))
#seqdftemp <- seqdftemp[c(2:160),]
#seqdf$Sequences<-seqdftemp
seqdf$Sequences <- gsub("-", "", seqdf$Sequences)
#seqdf <- seqdf[order(seqdf$Sample_ID),]
write.csv(seqdf, "mtDNAseqs.csv")
```


## Add new sample IDs by site
```{r}
# Allegheny
ALL <- seqdf[c(3:24),]
View(ALL)
ALL <- ALL[c(1,12,16,17,18,19,20,21,22,2,3,4,5,6,7,8,9,10,11,13,14,15),] # Reorder columns
ALL$New_ID <- 1:nrow(ALL) # Create New_ID column
ALLvec <- c("ALL1", "ALL2","ALL3", "ALL4", "ALL5", "ALL6", "ALL7", "ALL8", "ALL9", "ALL10", "ALL11", "ALL12", "ALL13", "ALL14", "ALL15", "ALL16", "ALL17", "ALL18", "ALL19", "ALL20", "ALL21", "ALL22") # Create a vector of new sample IDs
ALL$New_ID <- rep.int(ALLvec, nrow(ALL)/22) # Allocate new IDs
ALL$Population <- 1 # Create Population column

# Chippewa
CHIP <- seqdf[c(25:43),]
View(CHIP)
CHIP <- CHIP[c(1,12,14,15,16,17,18,19,2,3,4,5,6,7,8,9,10,11,13),] # Reorder columns
CHIP$New_ID <- 1:nrow(CHIP) # Create New_ID column
CHIPvec <- c("CHIP1", "CHIP2","CHIP3", "CHIP4", "CHIP5", "CHIP6", "CHIP7", "CHIP8", "CHIP9", "CHIP10", "CHIP11", "CHIP12", "CHIP13", "CHIP14", "CHIP15", "CHIP16", "CHIP17", "CHIP18", "CHIP19") # Create a vector of new sample IDs
CHIP$New_ID <- rep.int(CHIPvec, nrow(CHIP)/19) # CHIPocate new IDs
CHIP$Population <- 2 # Create Population column

# Meramec
MER <- seqdf[-c(1:43),]
MER <- MER[-c(10:53),]
MER <- MER[-c(12:13),]
MER <- MER[-c(27:70),]
View(MER)
MER$New_ID <- 1:nrow(MER) # Create New_ID column
MER <- MER[c(1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,13,22,23,24,25,26),] # Reorder columns
MERvec <- c("MER1", "MER2","MER3", "MER4", "MER5", "MER6", "MER7", "MER8", "MER9", "MER10", "MER11", "MER12", "MER13", "MER14", "MER15", "MER16", "MER17", "MER18", "MER19", "MER20", "MER21", "MER22", "MER23", "MER24", "MER25", "MER26") # Create a vector of new sample IDs
MER$New_ID <- rep.int(MERvec, nrow(MER)/26) # MERocate new IDs
MER$Population <- 3 # Create Population column

# Mississippi
MISS <- seqdf[-c(3:52),]
MISS <- MISS[-c(47:110),]
View(MISS)
MISS$New_ID <- 1:nrow(MISS) # Create New_ID column
MISS <- MISS[c(3,14,25,36,42,43,44,45,46,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,35,37,38,39,40,41,1,2),] # Reorder columns
MISSvec <- c("MISS1", "MISS2","MISS3", "MISS4", "MISS5", "MISS6", "MISS7", "MISS8", "MISS9", "MISS10", "MISS11", "MISS12", "MISS13", "MISS14", "MISS15", "MISS16", "MISS17", "MISS18", "MISS19", "MISS20", "MISS21", "MISS22", "MISS23", "MISS24", "MISS25", "MISS26", "MISS27", "MISS28", "MISS29", "MISS30", "MISS31","MISS32", "MISS33", "MISS34", "MISS35", "MISS36", "MISS37", "MISS38", "MISS39", "MISS40", "MISS41", "MISS42", "MISS43", "MISS44", "MISS45", "MISS46") # Create a vector of new sample IDs
MISS$New_ID <- rep.int(MISSvec, nrow(MISS)/46) # MISSocate new IDs
MISS$Population <- 4 # Create Population column

# Tippecanoe
TIPP <- seqdf[c(126:144),]
View(TIPP)
TIPP$New_ID <- 1:nrow(TIPP) # Create New_ID column
TIPP <- TIPP[c(1,12,13,14,15,16,17,18,19,2,3,4,5,6,7,8,9,10,11),] # Reorder columns
TIPPvec <- c("TIPP1", "TIPP2","TIPP3", "TIPP4", "TIPP5", "TIPP6", "TIPP7", "TIPP8", "TIPP9", "TIPP10", "TIPP11", "TIPP12", "TIPP13", "TIPP14", "TIPP15", "TIPP16", "TIPP17", "TIPP18", "TIPP19") # Create a vector of new sample IDs
TIPP$New_ID <- rep.int(TIPPvec, nrow(TIPP)/19) # TIPPocate new IDs
TIPP$Population <- 5 # Create Population column

# Tennessee
TN <- seqdf[c(145:152),]
View(TN)
TN$New_ID <- 1:nrow(TN) # Create New_ID column
TNvec <- c("TN1", "TN2", "TN3", "TN4", "TN5", "TN6", "TN7", "TN8") # Create a vector of new sample IDs
TN$New_ID <- rep.int(TNvec, nrow(TN)/8) # Allocate new IDs
TN$Population <- 6 # Create Population column

# Wisconsin
WIS <- seqdf[-c(1:98),] # Trim dataset to only WIS samples
WIS <- WIS[-c(3:17),]
WIS <- WIS[-c(13:39),]
WIS <- WIS[-c(18),]
View(WIS)
WIS$New_ID <- 1:nrow(WIS) # Create New_ID column
WIS <- WIS[c(1,2,3,5,6,7,8,9,10,11,12,4,13,14,15,16,17),] # Reorder rows
WISvec <- c("WIS1", "WIS2","WIS3", "WIS4", "WIS5", "WIS6", "WIS7", "WIS8", "WIS9", "WIS10", "WIS11", "WIS12", "WIS13", "WIS14", "WIS15", "WIS16", "WIS17") # Create a vector of new sample IDs
WIS$New_ID <- rep.int(WISvec, nrow(WIS)/17) # WISocate new IDs
WIS$Population <- 7 # Create Population column

# Merge datasets
genos <- merge(ALL, CHIP, all= T) 
genos <- merge(genos, MER, all=T)
genos <- merge(genos, MISS, all=T)
genos <- merge(genos, TIPP, all=T)
genos <- merge(genos, TN, all=T)
genos <- merge(genos, WIS, all=T)

# Order dataset
genos <- genos[order(genos$New_ID),]
genos <- genos[,c(1,3,4,2)]

# Write file to fasta
genos <- genos[,-c(1,3)]
write.csv(genos, "mtDNA_genalex.csv")
df.fasta <- dataframe2fas(genos, file="df.fasta")
write.fasta(df.fasta, "mtDNA_sheepnose.fasta")
```

